import type { WriteXThemePackage } from "./themeSchema.ts";

export const DEFAULT_THEME_ID = "default";

const commonMapping: WriteXThemePackage["mapping"] = {
  document: "document",
  paragraph: "paragraph",
  heading1: "heading1",
  heading2: "heading2",
  heading3: "heading3",
  heading4: "heading3",
  heading5: "heading3",
  heading6: "heading3",
  strong: "strong",
  emphasis: "emphasis",
  delete: "delete",
  blockquote: "blockquote",
  unorderedList: "unorderedList",
  orderedList: "orderedList",
  listItem: "listItem",
  link: "link",
  image: "image",
  imageCaption: "imageCaption",
  inlineCode: "inlineCode",
  codeBlock: "codeBlock",
  horizontalRule: "horizontalRule",
  table: "table",
  tableHead: "tableHead",
  tableBody: "tableBody",
  tableRow: "tableRow",
  tableHeaderCell: "tableHeaderCell",
  tableCell: "tableCell",
};

const defaultTheme: WriteXThemePackage = {
  schemaVersion: 1,
  manifest: {
    id: DEFAULT_THEME_ID,
    name: "默认",
    version: "1.0.0",
    author: "WriteX",
    license: "MIT",
    sourceUrl: "https://github.com/pakco77/WriteX",
    description: "WriteX 原创的克制绿色公众号排版。",
    minWriteXVersion: "0.4.0",
  },
  tokens: {
    accent: "#35c46a",
    ink: "#222222",
    muted: "#66736b",
  },
  components: {
    document: { template: '<section style="box-sizing:border-box; color:#222222; background:#ffffff; font-family:-apple-system, BlinkMacSystemFont, PingFang SC, sans-serif; font-size:15px; line-height:1.75; word-break:break-word">{{children}}</section>' },
    paragraph: { template: '<p style="margin:8px 8px 16px; color:#37433b; font-size:15px; line-height:1.75; text-align:left">{{children}}</p>' },
    heading1: { template: '<h1 style="margin:28px 8px 20px; color:#17231b; font-size:24px; line-height:1.35; font-weight:700; text-align:left">{{children}}</h1>' },
    heading2: { template: '<h2 style="margin:28px 8px 16px; color:#17231b; font-size:18px; line-height:1.5; font-weight:700; border-left:4px solid #35c46a; padding-left:10px">{{children}}</h2>' },
    heading3: { template: '<h3 style="margin:22px 8px 12px; color:#2b4734; font-size:16px; line-height:1.5; font-weight:700">{{children}}</h3>' },
    strong: { template: '<strong style="color:#111111; font-weight:700">{{children}}</strong>' },
    emphasis: { template: '<em style="color:#245c36; font-style:normal; font-weight:600">{{children}}</em>' },
    delete: { template: '<span style="color:#849087; text-decoration:line-through">{{children}}</span>' },
    blockquote: { template: '<blockquote style="margin:18px 8px; padding:12px 16px; color:#536158; background:#f2faf4; border-left:3px solid #35c46a; line-height:1.7">{{children}}</blockquote>' },
    unorderedList: { template: '<ul style="margin:8px 8px 16px; padding-left:22px; color:#37433b">{{children}}</ul>' },
    orderedList: { template: '<ol style="margin:8px 8px 16px; padding-left:22px; color:#37433b">{{children}}</ol>' },
    listItem: { template: '<li style="margin:5px 0; line-height:1.7">{{children}}</li>' },
    link: { template: '<a href="{{src}}" style="color:#208346; text-decoration:underline">{{children}}</a>' },
    image: { template: '<section style="margin:20px 8px; text-align:center"><img src="{{src}}" alt="{{alt}}" style="max-width:100%; height:auto; border-radius:8px"></section>' },
    imageCaption: { template: '<p style="margin:6px 8px 18px; color:#8a948d; font-size:12px; line-height:1.5; text-align:center">{{caption}}</p>' },
    inlineCode: { template: '<code style="padding:2px 5px; color:#225c36; background:#eff7f1; border-radius:4px; font-family:SFMono-Regular, Consolas, monospace; font-size:13px">{{content}}</code>' },
    codeBlock: { template: '<pre style="margin:18px 8px; padding:14px; color:#e9f7ed; background:#18231c; border-radius:8px; overflow-x:auto; font-size:13px; line-height:1.6"><code>{{content}}</code></pre>' },
    horizontalRule: { template: '<hr style="margin:28px 8px; border:0; border-top:1px solid #dce8df">' },
    table: { template: '<table cellpadding="0" cellspacing="0" border="0" style="width:100%; margin:16px 0; border-collapse:collapse; font-size:14px">{{children}}</table>' },
    tableHead: { template: '<thead style="background:#eff7f1">{{children}}</thead>' },
    tableBody: { template: '<tbody>{{children}}</tbody>' },
    tableRow: { template: '<tr>{{children}}</tr>' },
    tableHeaderCell: { template: '<th style="padding:9px 8px; border:1px solid #dce8df; color:#1f4e30; font-weight:700; text-align:left">{{children}}</th>' },
    tableCell: { template: '<td style="padding:9px 8px; border:1px solid #e5ece7; color:#465249; line-height:1.6; vertical-align:top">{{children}}</td>' },
  },
  mapping: commonMapping,
};

const xiaoheiTheme: WriteXThemePackage = {
  schemaVersion: 1,
  manifest: {
    id: "xiaohei",
    name: "小黑",
    version: "1.0.0",
    author: "pakco",
    license: "MIT",
    sourceUrl: "3_审核与自动化/排版/公众号排版规范-半个造物主 乘百.md",
    description: "用户指定的小黑灰度排版；只映射原文语义，不注入署名、关注数或固定结尾。",
    minWriteXVersion: "0.4.0",
  },
  tokens: {
    "authority-sha256": "6109e161cb7973984cad697474393044305da8a576a0cab3186126f797f8263c",
    ink: "rgb(0, 0, 0)",
    body: "rgb(89, 89, 89)",
    muted: "rgb(178, 178, 178)",
    "heading-background": "rgb(25, 26, 36)",
  },
  components: {
    document: { template: '<section style="box-sizing:border-box; color:rgb(89, 89, 89); background:rgb(255, 255, 255); font-family:-apple-system, BlinkMacSystemFont, PingFang SC, sans-serif; font-size:15px; line-height:1.75; word-break:break-word">{{children}}</section>' },
    paragraph: { template: '<p style="margin:8px 12px 16px; color:rgb(89, 89, 89); font-size:15px; line-height:1.75; font-weight:400; text-align:left; text-indent:0">{{children}}</p>' },
    heading1: { template: '<h1 style="margin:28px 12px 20px; color:rgb(0, 0, 0); font-size:22px; line-height:1.5; font-weight:700; text-align:left">{{children}}</h1>' },
    heading2: { template: '<h2 style="margin:26px 12px 16px; color:rgb(255, 255, 255); background:rgb(25, 26, 36); font-family:PingFang SC, sans-serif; font-size:15px; line-height:1.75; font-weight:700; padding:0 6px">{{children}}</h2>' },
    heading3: { template: '<h3 style="margin:22px 12px 14px; color:rgb(0, 0, 0); font-size:15px; line-height:1.75; font-weight:700">{{children}}</h3>' },
    strong: { template: '<strong style="color:rgb(0, 0, 0); font-weight:700; font-style:normal">{{children}}</strong>' },
    emphasis: { template: '<strong style="color:rgb(0, 0, 0); font-weight:700; font-style:normal">{{children}}</strong>' },
    delete: { template: '<span style="color:rgb(178, 178, 178); text-decoration:line-through">{{children}}</span>' },
    blockquote: { template: '<blockquote style="margin:16px 12px; padding:10px 14px; color:rgb(89, 89, 89); border-left:2px solid rgb(178, 178, 178); font-size:14px; line-height:1.75">{{children}}</blockquote>' },
    unorderedList: { template: '<ul style="margin:8px 12px 16px; padding-left:22px; color:rgb(89, 89, 89); font-size:15px; line-height:1.75">{{children}}</ul>' },
    orderedList: { template: '<ol style="margin:8px 12px 16px; padding-left:22px; color:rgb(89, 89, 89); font-size:15px; line-height:1.75">{{children}}</ol>' },
    listItem: { template: '<li style="margin:4px 0; line-height:1.75">{{children}}</li>' },
    link: { template: '<a href="{{src}}" style="color:rgb(25, 26, 36); text-decoration:underline">{{children}}</a>' },
    image: { template: '<section style="margin:20px 12px; text-align:center"><img src="{{src}}" alt="{{alt}}" style="max-width:677px; width:100%; height:auto"></section>' },
    imageCaption: { template: '<p style="margin:6px 12px 18px; color:rgb(178, 178, 178); font-size:12px; line-height:1.6; text-align:center">{{caption}}</p>' },
    inlineCode: { template: '<code style="padding:2px 4px; color:rgb(25, 26, 36); background:rgb(245, 245, 245); font-family:SFMono-Regular, Consolas, monospace; font-size:13px">{{content}}</code>' },
    codeBlock: { template: '<pre style="margin:16px 12px; padding:12px; color:rgb(89, 89, 89); background:rgb(245, 245, 245); overflow-x:auto; font-size:13px; line-height:1.6"><code>{{content}}</code></pre>' },
    horizontalRule: { template: '<hr style="margin:26px 12px; border:0; border-top:1px solid rgba(0, 0, 0, 0.1)">' },
    table: { template: '<table cellpadding="0" cellspacing="0" border="0" style="width:100%; margin:16px 0; border-collapse:collapse; font-size:14px">{{children}}</table>' },
    tableHead: { template: '<thead>{{children}}</thead>' },
    tableBody: { template: '<tbody>{{children}}</tbody>' },
    tableRow: { template: '<tr>{{children}}</tr>' },
    tableHeaderCell: { template: '<th style="padding:8px; border:1px solid rgb(225, 225, 225); color:rgb(0, 0, 0); font-weight:700; text-align:left">{{children}}</th>' },
    tableCell: { template: '<td style="padding:8px; border:1px solid rgb(225, 225, 225); color:rgb(89, 89, 89); font-size:14px; line-height:1.6; text-align:justify; vertical-align:top">{{children}}</td>' },
  },
  mapping: commonMapping,
};

const compactTheme: WriteXThemePackage = {
  schemaVersion: 1,
  manifest: {
    id: "compact",
    name: "精简排版（扩容）",
    version: "1.0.0",
    author: "WriteX",
    license: "MIT",
    sourceUrl: "https://github.com/pakco77/WriteX",
    description: "保留 Markdown 语义，去除装饰性内联样式以压缩微信草稿 HTML。",
    minWriteXVersion: "0.5.9",
  },
  tokens: {},
  components: {
    document: { template: "<section>{{children}}</section>" },
    paragraph: { template: "<p>{{children}}</p>" },
    heading1: { template: "<h1>{{children}}</h1>" },
    heading2: { template: "<h2>{{children}}</h2>" },
    heading3: { template: "<h3>{{children}}</h3>" },
    strong: { template: "<strong>{{children}}</strong>" },
    emphasis: { template: "<em>{{children}}</em>" },
    delete: { template: "<span style=\"text-decoration:line-through\">{{children}}</span>" },
    blockquote: { template: "<blockquote>{{children}}</blockquote>" },
    unorderedList: { template: "<ul>{{children}}</ul>" },
    orderedList: { template: "<ol>{{children}}</ol>" },
    listItem: { template: "<li>{{children}}</li>" },
    link: { template: '<a href="{{src}}">{{children}}</a>' },
    image: { template: '<img src="{{src}}" alt="{{alt}}">' },
    imageCaption: { template: "<p>{{caption}}</p>" },
    inlineCode: { template: "<code>{{content}}</code>" },
    codeBlock: { template: "<pre><code>{{content}}</code></pre>" },
    horizontalRule: { template: "<hr>" },
    table: { template: "<table>{{children}}</table>" },
    tableHead: { template: "<thead>{{children}}</thead>" },
    tableBody: { template: "<tbody>{{children}}</tbody>" },
    tableRow: { template: "<tr>{{children}}</tr>" },
    tableHeaderCell: { template: "<th>{{children}}</th>" },
    tableCell: { template: "<td>{{children}}</td>" },
  },
  mapping: commonMapping,
};

export const BUILTIN_THEMES: Readonly<Record<string, WriteXThemePackage>> = Object.freeze({
  default: defaultTheme,
  xiaohei: xiaoheiTheme,
  compact: compactTheme,
});

export function getBuiltinTheme(id: string): WriteXThemePackage | undefined {
  return BUILTIN_THEMES[id];
}
